### ISSUE TITLE
Missing Dependency (PHP Zip)?

### ISSUE THREAD

**Issue by webstationhq** [pikim/grav-plugin-events#13]
Tried to install using lc.  I have the problems plugin installed.  Should the events plugin try to detect if ZipArchive is present before trying to run?  Just a thought.

@MacBook-Pro htdocs % bin/gpm install events

GPM Releases Configuration: Stable

The following dependencies need to be installed...
  |- Package datetools

Install this package? [Y|n] Y
Preparing to install Date Tools [v1.0.6]
  |- Downloading package...   100%%7%
  |- Checking destination...  ok
  |- Installing package...  
Fatal error: Uncaught Error: Class 'ZipArchive' not found in /Applications/MAMP/htdocs/system/src/Grav/Common/GPM/Installer.php:175
Stack trace:
#0 /Applications/MAMP/htdocs/system/src/Grav/Common/GPM/Installer.php(104): Grav\Common\GPM\Installer::unZip('/Applications/M...', '/Applications/M...')
#1 /Applications/MAMP/htdocs/system/src/Grav/Console/Gpm/InstallCommand.php(655): Grav\Common\GPM\Installer::install('/Applications/M...', '/Applications/M...', Array)
#2 /Applications/MAMP/htdocs/system/src/Grav/Console/Gpm/InstallCommand.php(537): Grav\Console\Gpm\InstallCommand->installPackage(Object(Grav\Common\GPM\Remote\Package), false)
#3 /Applications/MAMP/htdocs/system/src/Grav/Console/Gpm/InstallCommand.php(339): Grav\Console\Gpm\InstallCommand->processGpm(Object(Grav\Common\GPM\Remote\Package), false)
#4 /Applications/MAMP/htdocs/system/src/Grav/Console/Gpm/InstallCommand.php(309): Grav\Console\Gpm\InstallCommand->processPackage(Object(Grav\Common\GPM\Remote\Package), false)
#5 /Applications/MAMP/htdocs/system/src/Grav in /Applications/MAMP/htdocs/system/src/Grav/Common/GPM/Installer.php on line 175

**Comment by webstationhq** [comment]
Please note that it installed fine from Grav Admin plugins

**Comment by pikim** [comment]
Is this still relevant? I never got similar feedback.
